# This file generates the GitHub Actions matrix.
---
include:
# Central = Right
  # - board: seeeduino_xiao_ble
  #   shield: lism_left rgbled_adapter
  #   snippet: "lism-peripheral non-trackball-peripheral"
  #   artifact-name: lism_left_peripheral_non_trackball
  # - board: seeeduino_xiao_ble
  #   shield: lism_left rgbled_adapter
  #   snippet: "lism-peripheral 4waystick-peripheral"
  #   artifact-name: lism_left_peripheral_4waystick
  # - board: seeeduino_xiao_ble
  #   shield: lism_left rgbled_adapter
  #   snippet: "lism-peripheral trackball-peripheral"
  #   artifact-name: lism_left_peripheral_trackball
  # - board: seeeduino_xiao_ble
  #   shield: lism_right rgbled_adapter
  #   snippet: "lism-central studio-rpc-usb-uart non-trackball-central"
  #   artifact-name: lism_right_central_non_trackball
  # - board: seeeduino_xiao_ble
  #   shield: lism_right rgbled_adapter
  #   snippet: "lism-central studio-rpc-usb-uart 4waystick-central"
  #   artifact-name: lism_right_central_4waystick
  # - board: seeeduino_xiao_ble
  #   shield: lism_right rgbled_adapter
  #   snippet: "lism-central studio-rpc-usb-uart trackball-central"
  #   artifact-name: lism_right_central_trackball

# Central = Left
  - board: seeeduino_xiao_ble
    shield: lism_right rgbled_adapter
    snippet: "lism-peripheral non-trackball-peripheral"
    artifact-name: lism_right_peripheral_non_trackball
  - board: seeeduino_xiao_ble
    shield: lism_right rgbled_adapter
    snippet: "lism-peripheral 4waystick-peripheral"
    artifact-name: lism_right_peripheral_4waystick
  - board: seeeduino_xiao_ble
    shield: lism_right rgbled_adapter
    snippet: "lism-peripheral trackball-peripheral"
    artifact-name: lism_right_peripheral_trackball
  - board: seeeduino_xiao_ble
    shield: lism_left rgbled_adapter
    snippet: "lism-central studio-rpc-usb-uart non-trackball-central"
    artifact-name: lism_left_central_non_trackball
  - board: seeeduino_xiao_ble
    shield: lism_left rgbled_adapter
    snippet: "lism-central studio-rpc-usb-uart 4waystick-central"
    artifact-name: lism_left_central_4waystick
  - board: seeeduino_xiao_ble
    shield: lism_left rgbled_adapter
    snippet: "lism-central studio-rpc-usb-uart trackball-central"
    artifact-name: lism_left_central_trackball
  
  # Reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset-seeeduino_xiao_ble-zmk
